name : Use Variable
on: [workflow_dispatch]

env:
  APP_NAME: my-spring-app

  jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret
        run: |
          echo "TEsting passing variable in pipeline"
          echo "App name:$APP_NAME"
          echo "Environment: ${{ vars.ENV_NAME }}"
